"""The app catalogue: what the agent knows about installed programs.

DATA ONLY — no logic, no I/O. `apps.py` reads this table to turn a spoken name
("brave", "bloc-notes", "parametres") into a launch target.

Each entry:
  keys   : the names a user (or the model) may say, French and English.
  exes   : executable names. Also the process names the launched window may
           belong to, which is what makes launch verification trustworthy.
  paths  : usual install locations (checked first).
  globs  : versioned installs (Discord\\app-1.0.1234\\Discord.exe, Slack\\app-*).
  titles : substrings of the window titles the app opens (used to verify).

To add an app: add one entry here, copying an existing line. Keep the most
common key first — it becomes the canonical name in the reports.
"""
from .paths import (
    LOCAL_APPDATA, PROGRAM_DATA, PROGRAM_FILES, PROGRAM_FILES_X86,
    ROAMING_APPDATA, WINDOWS_DIR, join,
)

APPS = [
    # --- browsers
    {"keys": ("brave", "brave browser", "navigateur brave", "brave-browser"),
     "exes": ("brave.exe",),
     "paths": (join(PROGRAM_FILES, "BraveSoftware", "Brave-Browser", "Application", "brave.exe"),
               join(PROGRAM_FILES_X86, "BraveSoftware", "Brave-Browser", "Application", "brave.exe"),
               join(LOCAL_APPDATA, "BraveSoftware", "Brave-Browser", "Application", "brave.exe")),
     "titles": ("brave",)},
    {"keys": ("chrome", "google chrome", "navigateur chrome"),
     "exes": ("chrome.exe",),
     "paths": (join(PROGRAM_FILES, "Google", "Chrome", "Application", "chrome.exe"),
               join(PROGRAM_FILES_X86, "Google", "Chrome", "Application", "chrome.exe"),
               join(LOCAL_APPDATA, "Google", "Chrome", "Application", "chrome.exe")),
     "titles": ("chrome", "google chrome")},
    {"keys": ("edge", "microsoft edge"),
     "exes": ("msedge.exe",),
     "paths": (join(PROGRAM_FILES_X86, "Microsoft", "Edge", "Application", "msedge.exe"),
               join(PROGRAM_FILES, "Microsoft", "Edge", "Application", "msedge.exe")),
     "titles": ("edge",)},
    {"keys": ("firefox", "mozilla firefox"),
     "exes": ("firefox.exe",),
     "paths": (join(PROGRAM_FILES, "Mozilla Firefox", "firefox.exe"),
               join(PROGRAM_FILES_X86, "Mozilla Firefox", "firefox.exe")),
     "titles": ("firefox", "mozilla")},
    {"keys": ("opera", "opera gx"),
     "exes": ("opera.exe", "launcher.exe"),
     "paths": (join(LOCAL_APPDATA, "Programs", "Opera", "launcher.exe"),
               join(PROGRAM_FILES, "Opera", "launcher.exe"),
               join(PROGRAM_FILES_X86, "Opera", "launcher.exe")),
     "titles": ("opera",)},
    # --- chat / social
    {"keys": ("discord",),
     "exes": ("discord.exe",),
     "globs": (join(LOCAL_APPDATA, "Discord", "app-*", "Discord.exe"),
               join(PROGRAM_FILES, "Discord", "app-*", "Discord.exe")),
     "paths": (),
     "titles": ("discord",)},
    {"keys": ("whatsapp",), "exes": ("whatsapp.exe",), "paths": (), "titles": ("whatsapp",)},
    {"keys": ("telegram",), "exes": ("telegram.exe",), "paths": (), "titles": ("telegram",)},
    {"keys": ("signal",), "exes": ("signal.exe",), "paths": (), "titles": ("signal",)},
    {"keys": ("slack",), "exes": ("slack.exe",),
     "globs": (join(LOCAL_APPDATA, "slack", "app-*", "slack.exe"),),
     "paths": (), "titles": ("slack",)},
    {"keys": ("teams", "microsoft teams"), "exes": ("ms-teams.exe", "teams.exe"),
     "paths": (join(LOCAL_APPDATA, "Microsoft", "WindowsApps", "ms-teams.exe"),),
     "titles": ("teams",)},
    {"keys": ("zoom", "zoom meetings"), "exes": ("zoom.exe",),
     "paths": (join(ROAMING_APPDATA, "Zoom", "bin", "Zoom.exe"),), "titles": ("zoom",)},
    {"keys": ("outlook", "microsoft outlook"), "exes": ("outlook.exe",),
     "paths": (), "titles": ("outlook",)},
    # --- media
    {"keys": ("spotify",), "exes": ("spotify.exe",),
     "paths": (join(ROAMING_APPDATA, "Spotify", "Spotify.exe"),
               join(LOCAL_APPDATA, "Microsoft", "WindowsApps", "Spotify.exe")),
     "titles": ("spotify",)},
    {"keys": ("vlc", "vlc media player"), "exes": ("vlc.exe",),
     "paths": (join(PROGRAM_FILES, "VideoLAN", "VLC", "vlc.exe"),
               join(PROGRAM_FILES_X86, "VideoLAN", "VLC", "vlc.exe")),
     "titles": ("vlc",)},
    {"keys": ("steam",), "exes": ("steam.exe",),
     "paths": (join(PROGRAM_FILES_X86, "Steam", "steam.exe"),
               join(PROGRAM_FILES, "Steam", "steam.exe")),
     "titles": ("steam",)},
    {"keys": ("epic games", "epic games launcher", "epic"),
     "exes": ("EpicGamesLauncher.exe",),
     "paths": (join(PROGRAM_FILES_X86, "Epic Games", "Launcher", "Portal", "Binaries", "Win32",
                    "EpicGamesLauncher.exe"),
               join(PROGRAM_FILES, "Epic Games", "Launcher", "Portal", "Binaries", "Win32",
                    "EpicGamesLauncher.exe")),
     "titles": ("epic games",)},
    {"keys": ("obs", "obs studio"), "exes": ("obs64.exe", "obs32.exe"),
     "paths": (join(PROGRAM_FILES, "obs-studio", "bin", "64bit", "obs64.exe"),),
      "titles": ("obs",)},
    {"keys": ("premiere pro", "adobe premiere pro", "premiere", "adobe premiere"),
     "exes": ("Adobe Premiere Pro.exe",),
     "globs": (join(PROGRAM_FILES, "Adobe", "Adobe Premiere Pro *", "Adobe Premiere Pro.exe"),),
     "paths": (), "titles": ("adobe premiere pro", "premiere pro")},
    {"keys": ("capcut", "cap cut"), "exes": ("CapCut.exe",),
     "globs": (join(LOCAL_APPDATA, "CapCut", "Apps", "*", "CapCut.exe"),
               join(LOCAL_APPDATA, "Programs", "CapCut", "CapCut.exe")),
     "paths": (join(PROGRAM_FILES, "CapCut", "CapCut.exe"),), "titles": ("capcut",)},
    {"keys": ("davinci resolve", "resolve", "davinci"), "exes": ("Resolve.exe",),
     "paths": (join(PROGRAM_FILES, "Blackmagic Design", "DaVinci Resolve", "Resolve.exe"),),
     "titles": ("davinci resolve",)},
    # --- system & productivity
    {"keys": ("explorer", "file explorer", "explorateur", "explorateur de fichiers",
              "windows explorer", "mes documents"),
     "exes": ("explorer.exe",),
     "paths": (join(WINDOWS_DIR, "explorer.exe"),),
     "titles": ("explorateur", "file explorer", "explorer")},
    {"keys": ("notepad", "bloc-notes", "bloc notes", "windows notepad"),
     "exes": ("notepad.exe",),
     "paths": (join(WINDOWS_DIR, "System32", "notepad.exe"),),
     "titles": ("notepad", "bloc-notes")},
    {"keys": ("notepad++", "npp", "notepad plus plus"),
     "exes": ("notepad++.exe",),
     "paths": (join(PROGRAM_FILES, "Notepad++", "notepad++.exe"),
               join(PROGRAM_FILES_X86, "Notepad++", "notepad++.exe")),
     "titles": ("notepad++",)},
    {"keys": ("paint", "mspaint"), "exes": ("mspaint.exe",), "paths": (),
     "titles": ("paint",)},
    {"keys": ("calculator", "calculatrice", "calc"),
     "exes": ("calc.exe", "Calculator.exe"),
     "paths": (), "titles": ("calculatrice", "calculator")},
    {"keys": ("cmd", "command prompt", "invite de commandes"),
     "exes": ("cmd.exe",), "paths": (), "titles": ("invite de commandes", "command prompt", "cmd")},
    {"keys": ("powershell", "power shell"),
     "exes": ("powershell.exe", "pwsh.exe"), "paths": (),
     "titles": ("powershell", "windows powershell")},
    {"keys": ("terminal", "windows terminal", "wt"),
     "exes": ("wt.exe",), "paths": (), "titles": ("terminal",)},
    {"keys": ("code", "vs code", "vscode", "visual studio code"),
     "exes": ("code.cmd", "code.exe"),
     "paths": (join(LOCAL_APPDATA, "Programs", "Microsoft VS Code", "Code.exe"),
               join(PROGRAM_FILES, "Microsoft VS Code", "Code.exe")),
     "titles": ("visual studio code",)},
    {"keys": ("word", "microsoft word"), "exes": ("winword.exe",), "paths": (),
     "titles": ("word",)},
    {"keys": ("excel", "microsoft excel"), "exes": ("excel.exe",), "paths": (),
     "titles": ("excel",)},
    {"keys": ("powerpoint", "microsoft powerpoint"), "exes": ("powerpnt.exe",),
     "paths": (), "titles": ("powerpoint",)},
    {"keys": ("onenote", "microsoft onenote"), "exes": ("onenote.exe",),
     "paths": (), "titles": ("onenote",)},
    {"keys": ("task manager", "gestionnaire des taches", "gestionnaire de taches"),
     "exes": ("taskmgr.exe",), "paths": (), "titles": ("gestionnaire des tâches", "task manager")},
    {"keys": ("settings", "parametres", "windows settings", "reglages"),
     "exes": ("SystemSettings.exe",), "paths": (), "titles": ("paramètres", "settings")},
    {"keys": ("control panel", "panneau de configuration"),
     "exes": ("control.exe",), "paths": (), "titles": ("panneau de configuration", "control panel")},
    {"keys": ("snipping tool", "capture d'ecran", "capture d ecran"),
     "exes": ("SnippingTool.exe", "ScreenSketch.exe"), "paths": (),
     "titles": ("snipping tool", "capture d’écran", "capture d'écran")},
    {"keys": ("photos", "photos windows"), "exes": ("Photos.exe",), "paths": (),
     "titles": ("photos",)},
    {"keys": ("7zip", "7-zip"), "exes": ("7zFM.exe",),
     "paths": (join(PROGRAM_FILES, "7-Zip", "7zFM.exe"),
               join(PROGRAM_FILES_X86, "7-Zip", "7zFM.exe")),
     "titles": ("7-zip",)},
    {"keys": ("winrar",), "exes": ("WinRAR.exe",),
     "paths": (join(PROGRAM_FILES, "WinRAR", "WinRAR.exe"),
               join(PROGRAM_FILES_X86, "WinRAR", "WinRAR.exe")),
     "titles": ("winrar",)},
    {"keys": ("git bash", "gitbash"), "exes": ("git-bash.exe",),
     "paths": (join(PROGRAM_FILES, "Git", "git-bash.exe"),
               join(PROGRAM_FILES_X86, "Git", "git-bash.exe")),
     "titles": ("git bash", "mintty")},
]

# Start-menu folders scanned for shortcuts (both machine-wide and per-user).
START_MENU_ROOTS = (
    join(PROGRAM_DATA, "Microsoft", "Windows", "Start Menu", "Programs"),
    join(ROAMING_APPDATA, "Microsoft", "Windows", "Start Menu", "Programs"),
)
